### ISSUE TITLE
Bobcat AEM-BDD install initialization error

### ISSUE THREAD

**Issue by thirunavookkarasu** [Cognifide/bobcat#225] opened 2018-02-22 17:22 UTC
I followed bobcat AEM-BDD installation steps for Hello world program. I followed the same in Mac OS. After successful installation, I run the "MVN CLEAN INSTALL" command from HelloWorld folder and it throws the Initialization error. How to run the HelloWorld program for AEM-BDD Archtype.

**Comment by discovermoi** [comment] 2018-04-20 02:29
Hi Thiru, Did you get an answer?

**Comment by mkrzyzanowski** [comment] 2018-04-23 13:52
Hi @thirunavookkarasu!
I'm closing the ticket for now. If the issue is still valid, please provide more info according to our latest [issue template](https://github.com/Cognifide/bobcat/blob/master/.github/ISSUE_TEMPLATE.md) and reopen it,

**Closed by mkrzyzanowski** 2018-04-23 13:52 UTC
